version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/WordPress
hooks:
  BeforeInstall:
    - location: scripts/install-dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/change-permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start-server.sh
    - location: scripts/create-test_db.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop-server.sh
      timeout: 300
      runas: root
